/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSustainabilityRouteImport } from './routes/_app.sustainability'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppPredictRouteImport } from './routes/_app.predict'
import { Route as AppMaintenanceRouteImport } from './routes/_app.maintenance'
import { Route as AppMachinesRouteImport } from './routes/_app.machines'
import { Route as AppFinanceRouteImport } from './routes/_app.finance'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAssistantRouteImport } from './routes/_app.assistant'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppMachinesIdRouteImport } from './routes/_app.machines.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSustainabilityRoute = AppSustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPredictRoute = AppPredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceRoute = AppMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)
const AppMachinesRoute = AppMachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppMachinesIdRoute = AppMachinesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMachinesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AppAlertsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/assistant': typeof AppAssistantRoute
  '/dashboard': typeof AppDashboardRoute
  '/finance': typeof AppFinanceRoute
  '/machines': typeof AppMachinesRouteWithChildren
  '/maintenance': typeof AppMaintenanceRoute
  '/predict': typeof AppPredictRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/sustainability': typeof AppSustainabilityRoute
  '/machines/$id': typeof AppMachinesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AppAlertsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/assistant': typeof AppAssistantRoute
  '/dashboard': typeof AppDashboardRoute
  '/finance': typeof AppFinanceRoute
  '/machines': typeof AppMachinesRouteWithChildren
  '/maintenance': typeof AppMaintenanceRoute
  '/predict': typeof AppPredictRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/sustainability': typeof AppSustainabilityRoute
  '/machines/$id': typeof AppMachinesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/assistant': typeof AppAssistantRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/machines': typeof AppMachinesRouteWithChildren
  '/_app/maintenance': typeof AppMaintenanceRoute
  '/_app/predict': typeof AppPredictRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sustainability': typeof AppSustainabilityRoute
  '/_app/machines/$id': typeof AppMachinesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alerts'
    | '/analytics'
    | '/assistant'
    | '/dashboard'
    | '/finance'
    | '/machines'
    | '/maintenance'
    | '/predict'
    | '/reports'
    | '/settings'
    | '/sustainability'
    | '/machines/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/alerts'
    | '/analytics'
    | '/assistant'
    | '/dashboard'
    | '/finance'
    | '/machines'
    | '/maintenance'
    | '/predict'
    | '/reports'
    | '/settings'
    | '/sustainability'
    | '/machines/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/alerts'
    | '/_app/analytics'
    | '/_app/assistant'
    | '/_app/dashboard'
    | '/_app/finance'
    | '/_app/machines'
    | '/_app/maintenance'
    | '/_app/predict'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/sustainability'
    | '/_app/machines/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sustainability': {
      id: '/_app/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof AppSustainabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/predict': {
      id: '/_app/predict'
      path: '/predict'
      fullPath: '/predict'
      preLoaderRoute: typeof AppPredictRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maintenance': {
      id: '/_app/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AppMaintenanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/machines': {
      id: '/_app/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof AppMachinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistant': {
      id: '/_app/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/machines/$id': {
      id: '/_app/machines/$id'
      path: '/$id'
      fullPath: '/machines/$id'
      preLoaderRoute: typeof AppMachinesIdRouteImport
      parentRoute: typeof AppMachinesRoute
    }
  }
}

interface AppMachinesRouteChildren {
  AppMachinesIdRoute: typeof AppMachinesIdRoute
}

const AppMachinesRouteChildren: AppMachinesRouteChildren = {
  AppMachinesIdRoute: AppMachinesIdRoute,
}

const AppMachinesRouteWithChildren = AppMachinesRoute._addFileChildren(
  AppMachinesRouteChildren,
)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppMachinesRoute: typeof AppMachinesRouteWithChildren
  AppMaintenanceRoute: typeof AppMaintenanceRoute
  AppPredictRoute: typeof AppPredictRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSustainabilityRoute: typeof AppSustainabilityRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppMachinesRoute: AppMachinesRouteWithChildren,
  AppMaintenanceRoute: AppMaintenanceRoute,
  AppPredictRoute: AppPredictRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSustainabilityRoute: AppSustainabilityRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
